# ============================================================
# Profile: Dufer (Camarón)
# ============================================================
INATrace.database.name = inatrace_duffer_stage
spring.security.oauth2.resourceserver.jwt.issuer-uri = http://localhost:8080/realms/dufer
inatrace.keycloak.admin.realm = dufer
