# ============================================================
# Profile: Fortaleza del Valle (Cacao)
# ============================================================
INATrace.database.name = inatrace_fortaleza_stage
spring.security.oauth2.resourceserver.jwt.issuer-uri = http://localhost:8080/realms/fortaleza
inatrace.keycloak.admin.realm = fortaleza
