# ============================================================
# Profile: Unocace (Cacao)
# ============================================================
INATrace.database.name = inatrace_unocace_stage
spring.security.oauth2.resourceserver.jwt.issuer-uri = http://localhost:8080/realms/unocace
inatrace.keycloak.admin.realm = unocace
