package com.abelium.inatrace.components.groupstockorder;

import com.abelium.inatrace.components.groupstockorder.api.ApiGroupStockOrder;
import com.abelium.inatrace.types.Language;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;

import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

@SpringBootTest
class SXSSFWorkbookExportTest {

    @Autowired
    private GroupStockOrderService groupStockOrderService;

    @Test
    void testExportGroupStockOrdersToExcelWithSXSSF() throws IOException {
        List<ApiGroupStockOrder> sampleOrders = new ArrayList<>();

        for (int i = 1; i <= 250; i++) {
            ApiGroupStockOrder order = new ApiGroupStockOrder();
            order.setFacilityName("Acopio Central " + i);
            order.setFarmerName("Productor Ejemplo " + i);
            order.setProductionDate(LocalDate.now());
            order.setInternalLotNumber("LOTE-" + i);
            order.setNoOfSacs(5L);
            order.setSemiProductName("Cacao Seco");
            order.setTotalQuantity(BigDecimal.valueOf(100.50));
            order.setFulfilledQuantity(BigDecimal.valueOf(50.00));
            order.setAvailableQuantity(BigDecimal.valueOf(50.50));
            order.setUnitLabel("kg");
            order.setDeliveryTime(LocalDate.now());
            order.setUpdateTimestamp(OffsetDateTime.now().toInstant());
            order.setAvailable(true);
            order.setWeekNumber(12);
            sampleOrders.add(order);
        }

        ByteArrayInputStream in = groupStockOrderService.generateExcelFile(sampleOrders, Language.ES, true);
        assertNotNull(in, "Export stream should not be null");

        // Verify the generated bytes can be successfully parsed back by standard POI reader
        try (Workbook readWorkbook = new XSSFWorkbook(in)) {
            Sheet sheet = readWorkbook.getSheetAt(0);
            assertNotNull(sheet, "Generated sheet should be readable");
            // Header + 250 rows
            assertEquals(251, sheet.getPhysicalNumberOfRows(), "Should have header + 250 data rows");
            assertEquals("Acopio Central 1", sheet.getRow(1).getCell(0).getStringCellValue());
        }
    }
}
